[package]
name = "kernel"
version = "0.1.0"
license = "MIT"
authors = ["Alexander Averyanov <alex@averyan.ru>"]
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
crunchy = "0.2.2"
spirv-std = "0.8.0"
